name: Purge PR images

on:
  pull_request_target:
    types:
      - closed
    paths:
      - "**/*"
      - "!.github/**" # Important: Exclude PRs related to .github from auto-run
      - "!.github/workflows/**" # Important: Exclude PRs related to .github from auto-run


permissions:
  contents: read
  packages: write

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      githubfolder: ${{ steps.filter.outputs.githubfolder }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            githubfolder:
              - '.github/**'

  purge-pr-package:
    name: Delete images from ghcr.io when PR is closed
    needs: check_paths
    if: needs.check_paths.outputs.githubfolder == 'false'
    runs-on: ubuntu-latest

    steps:
      - uses: chipkent/action-cleanup-package@1316a66015b82d745b57acbb6c570f2bb1d108f9 # v1.0.3
        id: cleanup
        continue-on-error: true
        with:
          package-name: ${{ github.event.repository.name }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        if: job.steps.cleanup.status == success()
        name: Delete untagged images from ghcr.io
        continue-on-error: true
        with:
          package-name: "teslamate"
          package-type: "container"
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
